Repository Chandler8/Musical-Mood-Generator, pull requests merged in 2020-07, with the labels that each got.

#8 Created Main Aspects of Front End UI
  assets/font-awesome-4.7.0/HELP-US-OUT.txt
  assets/font-awesome-4.7.0/css/font-awesome.css
  assets/font-awesome-4.7.0/css/font-awesome.min.css
  assets/font-awesome-4.7.0/fonts/FontAwesome.otf
  assets/font-awesome-4.7.0/fonts/fontawesome-webfont.eot
  assets/font-awesome-4.7.0/fonts/fontawesome-webfont.svg
  assets/font-awesome-4.7.0/fonts/fontawesome-webfont.ttf
  assets/font-awesome-4.7.0/fonts/fontawesome-webfont.woff
  assets/font-awesome-4.7.0/fonts/fontawesome-webfont.woff2
  assets/font-awesome-4.7.0/less/animated.less
  assets/font-awesome-4.7.0/less/bordered-pulled.less
  assets/font-awesome-4.7.0/less/core.less
  assets/font-awesome-4.7.0/less/fixed-width.less
  assets/font-awesome-4.7.0/less/font-awesome.less
  assets/font-awesome-4.7.0/less/icons.less
  assets/font-awesome-4.7.0/less/larger.less
  assets/font-awesome-4.7.0/less/list.less
  assets/font-awesome-4.7.0/less/mixins.less
  assets/font-awesome-4.7.0/less/path.less
  assets/font-awesome-4.7.0/less/rotated-flipped.less
  assets/font-awesome-4.7.0/less/screen-reader.less
  assets/font-awesome-4.7.0/less/stacked.less
  assets/font-awesome-4.7.0/less/variables.less
  assets/font-awesome-4.7.0/scss/_animated.scss
  assets/font-awesome-4.7.0/scss/_bordered-pulled.scss
  assets/font-awesome-4.7.0/scss/_core.scss
  assets/font-awesome-4.7.0/scss/_fixed-width.scss
  assets/font-awesome-4.7.0/scss/_icons.scss
  assets/font-awesome-4.7.0/scss/_larger.scss
  assets/font-awesome-4.7.0/scss/_list.scss
  assets/font-awesome-4.7.0/scss/_mixins.scss
  assets/font-awesome-4.7.0/scss/_path.scss
  assets/font-awesome-4.7.0/scss/_rotated-flipped.scss
  assets/font-awesome-4.7.0/scss/_screen-reader.scss
  assets/font-awesome-4.7.0/scss/_stacked.scss
  assets/font-awesome-4.7.0/scss/_variables.scss
  assets/font-awesome-4.7.0/scss/font-awesome.scss
  assets/queries.css
  index.html
  style.css
Labels: documentation, good first issue, help wanted

#45 Massive UI Overhaul
  index.html
  style.css
Labels: feature

#59 UI changes and fixes, addition of About page
  about.html
  home.html
  index.html
  past-mood.html
  script.js
  style.css
Labels: enhancement

#61 End Game UI Changes
  about.html
  home.html
  script.js
  style.css
Labels: enhancement

#63 fixed face bug
  about.html
  home.html
  index.html
  past-mood.html
  past.js
  script.js
  style.css
Labels: enhancement

#67 Added target blank attribute so links open in a new tab
  home.html
  script.js
Labels: enhancement

#68 Cleaned up queries
  assets/queries.css
Labels: documentation

#70 Deleted FA library to free up space and imported a CDN instead
  about.html
  assets/font-awesome-4.7.0/HELP-US-OUT.txt
  assets/font-awesome-4.7.0/css/font-awesome.css
  assets/font-awesome-4.7.0/css/font-awesome.min.css
  assets/font-awesome-4.7.0/fonts/FontAwesome.otf
  assets/font-awesome-4.7.0/fonts/fontawesome-webfont.eot
  assets/font-awesome-4.7.0/fonts/fontawesome-webfont.svg
  assets/font-awesome-4.7.0/fonts/fontawesome-webfont.ttf
  assets/font-awesome-4.7.0/fonts/fontawesome-webfont.woff
  assets/font-awesome-4.7.0/fonts/fontawesome-webfont.woff2
  assets/font-awesome-4.7.0/less/animated.less
  assets/font-awesome-4.7.0/less/bordered-pulled.less
  assets/font-awesome-4.7.0/less/core.less
  assets/font-awesome-4.7.0/less/fixed-width.less
  assets/font-awesome-4.7.0/less/font-awesome.less
  assets/font-awesome-4.7.0/less/icons.less
  assets/font-awesome-4.7.0/less/larger.less
  assets/font-awesome-4.7.0/less/list.less
  assets/font-awesome-4.7.0/less/mixins.less
  assets/font-awesome-4.7.0/less/path.less
  assets/font-awesome-4.7.0/less/rotated-flipped.less
  assets/font-awesome-4.7.0/less/screen-reader.less
  assets/font-awesome-4.7.0/less/stacked.less
  assets/font-awesome-4.7.0/less/variables.less
  assets/font-awesome-4.7.0/scss/_animated.scss
  assets/font-awesome-4.7.0/scss/_bordered-pulled.scss
  assets/font-awesome-4.7.0/scss/_core.scss
  assets/font-awesome-4.7.0/scss/_fixed-width.scss
  assets/font-awesome-4.7.0/scss/_icons.scss
  assets/font-awesome-4.7.0/scss/_larger.scss
  assets/font-awesome-4.7.0/scss/_list.scss
  assets/font-awesome-4.7.0/scss/_mixins.scss
  assets/font-awesome-4.7.0/scss/_path.scss
  assets/font-awesome-4.7.0/scss/_rotated-flipped.scss
  assets/font-awesome-4.7.0/scss/_screen-reader.scss
  assets/font-awesome-4.7.0/scss/_stacked.scss
  assets/font-awesome-4.7.0/scss/_variables.scss
  assets/font-awesome-4.7.0/scss/font-awesome.scss
  home.html
  index.html
  past-mood.html
  style.css
Labels: feature

#72 Updated README to represent the project
  Photos/Home1.JPG
  Photos/Home2.JPG
  Photos/Index1.JPG
  Photos/Mood1.JPG
  README.md
Labels: enhancement

#79 Added Custom FavIcon logo
  about.html
  assets/images/favicon-32x32.png
  home.html
  index.html
  past-mood.html
Labels: feature

#80 Final changes to README
  README.md
  assets/images/About1.JPG
  assets/images/Home1.JPG
  assets/images/Home2.JPG
  assets/images/Index1.JPG
  assets/images/Mood1.JPG
Labels: enhancement
